services:
  gitpull:
    build: .
    image: ghcr.io/mlenterman/docker-cron-git-pull
    environment:
      CRON: "*/5 * * * *"
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      - ./:/git
